### PR TITLE
Start partition producer in get metadata function

### LINKED ISSUE #635: Produce message to increased partition failed
### Description

There is a problem when I get metadata by `brod_client:get_metadata` function and calculate a partition index which I need to send a message; and the partitions may be increased and the brod client doesn't support start a process for those new partitions.

### Solution

Create new supervisor process for those new partitions in `do_get_metadata` function.

### PR DESCRIPTION
**Pull request by wiserfz**
Close #635

### CODE REVIEW

**Comment by wiserfz** [comment]
@zmstone hi, how about this PR

**Comment by zmstone** [comment]
@wiserfz 

thank you  for the pr. i just got back from vacation last week, slowly catching up with the missed activities.
I'll have a closer look soon during this week.

File: src/brod_client.erl [hunk 1]
```diff
@@ -981,6 +1000,74 @@ ensure_partition_workers(TopicName, State, F) ->
...
+    end,
+    lists:seq(OldPartitionCnt, OldPartitionCnt + (NewPartitionCnt - OldPartitionCnt) - 1)
+  ),
+
+  maybe_start_partition_producer(TopicsMetadata, Producers, Rest, ProducerSup, Configs);
+maybe_start_partition_producer(TopicsMetadata, Producers, [_Topic | Rest], ProducerSup, Configs) ->
+  maybe_start_partition_producer(TopicsMetadata, Producers, Rest, ProducerSup, Configs).
+
+-spec filter_topics([kpro:struct()]) -> #{topic() => non_neg_integer()}.
+filter_topics(TopicsMetadataArray) ->
```
Comment (zmstone) [inline src/brod_client.erl:1041]: I think we only get metadata for one topic at a time. i.e. this is a single element array.

Comment (zmstone) [reply src/brod_client.erl:1041]: sorry, i was wrong. the call to get_metdata supports topics array.

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,5 +1,8 @@
 # Changelog
 
+- 4.4.4
+  - Start supervisor process for the new increase partitions at `do_get_metadata` function.
```
Comment (zmstone) [inline CHANGELOG.md:4]: if the goal is to automatically start producers for newly discovered partitions, maybe brod_client should start a timer to periodically refresh partition counts for each topic which has a `producers_sup` started

File: src/brod_client.erl (hunk 1 above)
Comment (wiserfz) [reply src/brod_client.erl:1041]: yes, PR of #634 modified this function to supports topics array.

File: CHANGELOG.md (hunk 2 above)
Comment (wiserfz) [reply CHANGELOG.md:4]: At the beginning of this, I do really consider of this, maybe should start a process and automatically get kafka metadata then start new partition producer, and also I noticed the PR of #623 which already implemented this feature.

But, there are two reasons lead me open this PR:

1. The bug of function `brod_client:get_metadata/2`, this function only modify the number of topic partition in ETS table, but not start the partition producer.
2. In my situation, I get kafka metadata and calculate the partition index which I need to produce the message; use #623 feature, there may be a jet lag that the partition producer is not start when I need to produce.

Of course, #623 feature is good and I think it's not conflict with this PR.

What do you think?

File: src/brod_client.erl [hunk 3]
```diff
@@ -414,7 +415,15 @@ handle_call({get_transactional_coordinator, TransactionId}, _From, State) ->
   {Result, NewState} = do_get_transactional_coordinator(State, TransactionId),
   {reply, Result, NewState};
 handle_call({start_producer, TopicName, ProducerConfig}, _From, State) ->
-  {Reply, NewState} = do_start_producer(TopicName, ProducerConfig, State),
+  %% NOTE: Store ProducerConfig into the config in state
```
Comment (zmstone) [inline src/brod_client.erl]: producer config is per topic, it is already stored in supervisor child spec.
we can port get_childspec to brod_supervisor3

https://github.com/erlang/otp/blob/ec6323dd5065203737b0a48d074f116f0c1a2719/lib/stdlib/src/supervisor.erl#L752-L759

File: CHANGELOG.md (hunk 2 above)
Comment (zmstone) [reply CHANGELOG.md:4]: yes, i think i can agree to this.
but should also stop producers if some partitions are deleted ?

File: src/brod_client.erl [hunk 4]
```diff
@@ -981,6 +1000,74 @@ ensure_partition_workers(TopicName, State, F) ->
...
+    {TopicName, erlang:length(Partitions)}
+    || #{name := <<TopicName/binary>>, partitions := Partitions} <- NoErrors1,
+    is_list(Partitions)
+  ],
+
+  maps:from_list(NoErrors).
+
+-spec started_producers(pid()) -> #{topic() => non_neg_integer()}.
+started_producers(ProducerSup) ->
+  Producers = brod_supervisor3:which_children(ProducerSup),
```
Comment (zmstone) [inline src/brod_client.erl]: `brod_supervisor3:which_children(ProducerSup)` will give you the per-topic supervisors which supervises the per-partition workers

i think you'll need to do it like this:

```
started_producers(ProducerSup) ->
  TopicSups = which_producers(ProducerSup),
  lists:foldl(
    fun({Topic, Pid, _Type, _Mods}, Acc) when is_pid(Pid) ->
      PartitionWorkers = which_producers(Pid),
      case length(PartitionWorkers) of
        0 -> Acc;
        L -> Acc#{Topic => L}
    (_) ->
      Acc
    end, TopicSups).
```
and this
```
which_producers(Sup) ->
  try
    brod_supervisor3:which_children(Sup)
  catch
    _:_ ->
     []
  end.
```

**Review by zmstone — COMMENTED** [review]
please kindly add some tests

File: CHANGELOG.md (hunk 2 above)
Comment (wiserfz) [reply CHANGELOG.md:4]: > yes, i think i can agree to this. but should also stop producers if some partitions are deleted ?

kafka topic partitions only can be increased, it's can't be [reduced](https://kafka.apache.org/documentation/#basic_ops_modify_topic), so it doesn't need to be stopped.

File: src/brod_client.erl (hunk 3 above)
Comment (wiserfz) [reply src/brod_client.erl]: Done.

File: src/brod_client.erl (hunk 4 above)
Comment (wiserfz) [reply src/brod_client.erl]: Done.

**Comment by wiserfz** [comment]
> please kindly add some tests

Done.

File: CHANGELOG.md (hunk 2 above)
Comment (zmstone) [reply CHANGELOG.md:4]: yes, i'm referring to the case when a topic is deleted then created.

**Review by zmstone — APPROVED** [review]
this is good to merge, however, it would be nice to have another PR to address decreased partition count.

**Comment by wiserfz** [comment]
Thank you for merge this PR.

Would you release a tag for this feature?

**Comment by zmstone** [comment]
released 4.4.5

File: CHANGELOG.md (hunk 2 above)
Comment (BlueCollarChris) [reply CHANGELOG.md:4]: Just getting back around to #623, will get it moving again sorry for the delay
